/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:277719:
  appc.background(230);
} //_CODE_:window1:277719:

public void addBatteryClicked(GButton source, GEvent event) { //_CODE_:addBattery:517943:
  //components.add(new Component("battery", 100,100,100));
  //components.get(components.size()-1).drawMe();
  create_component_type = "battery";
  creating = true;
} //_CODE_:addBattery:517943:

public void addHorizontalWireClicked(GButton source, GEvent event) { //_CODE_:addHorizontalWire:391999:
  create_component_type = "wire";
  create_wire_orientation = true;
  creating = true;

} //_CODE_:addHorizontalWire:391999:

public void addVertWireClicked(GButton source, GEvent event) { //_CODE_:addVertWire:837893:
  create_component_type = "wire";
  create_wire_orientation = false;
  creating = true;

} //_CODE_:addVertWire:837893:

public void selectLayerPicked(GDropList source, GEvent event) { //_CODE_:selectLayer:676007:
  if(selectLayer.getSelectedText().contains("1")){
    selected_layer = layer_1;

  }else if(selectLayer.getSelectedText().contains("2")){
    selected_layer = layer_2;

  }else if(selectLayer.getSelectedText().contains("3")){
      selected_layer = layer_3;
  
  }else if(selectLayer.getSelectedText().contains("4")){
      selected_layer = layer_4;
      
      
  }
} //_CODE_:selectLayer:676007:

public void addLightbulbClicked(GButton source, GEvent event) { //_CODE_:addLightbulb:988807:
  create_component_type = "lightbulb";
  creating = true;
} //_CODE_:addLightbulb:988807:

public void deleteClicked(GButton source, GEvent event) { //_CODE_:delete:448134:
  deleting = true;
} //_CODE_:delete:448134:

public void showGridClicked(GCheckbox source, GEvent event) { //_CODE_:showGrid:970966:
  if(showGrid.isSelected()){
    gridShowing = true;
    
  }else{
    gridShowing = false;
  }
} //_CODE_:showGrid:970966:

public void clearClicked(GButton source, GEvent event) { //_CODE_:clear:830938:
  selected_layer.clear();
} //_CODE_:clear:830938:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 350, 350, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  addBattery = new GButton(window1, 100, 100, 30, 30);
  addBattery.setText("+");
  addBattery.addEventHandler(this, "addBatteryClicked");
  addHorizontalWire = new GButton(window1, 100, 150, 30, 30);
  addHorizontalWire.setText("+");
  addHorizontalWire.addEventHandler(this, "addHorizontalWireClicked");
  addVertWire = new GButton(window1, 100, 210, 30, 30);
  addVertWire.setText("+");
  addVertWire.addEventHandler(this, "addVertWireClicked");
  selectLayer = new GDropList(window1, 100, 60, 50, 120, 5, 10);
  selectLayer.setItems(loadStrings("list_676007"), 0);
  selectLayer.addEventHandler(this, "selectLayerPicked");
  batteryLabel = new GLabel(window1, 10, 105, 80, 20);
  batteryLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  batteryLabel.setText("Add Battery");
  batteryLabel.setOpaque(false);
  label1 = new GLabel(window1, 10, 140, 80, 50);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Add Horizontal Wire");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 10, 200, 80, 50);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Add Vertical Wire");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 10, 60, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Select Layer");
  label3.setOpaque(false);
  label4 = new GLabel(window1, 10, 260, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Add Lightbulb");
  label4.setOpaque(false);
  addLightbulb = new GButton(window1, 100, 255, 30, 30);
  addLightbulb.setText("+");
  addLightbulb.addEventHandler(this, "addLightbulbClicked");
  delete = new GButton(window1, 5, 300, 150, 30);
  delete.setText("DELETE COMPONENT");
  delete.addEventHandler(this, "deleteClicked");
  showGrid = new GCheckbox(window1, 10, 10, 120, 20);
  showGrid.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showGrid.setText("Show Grid");
  showGrid.setOpaque(false);
  showGrid.addEventHandler(this, "showGridClicked");
  showGrid.setSelected(true);
  clear = new GButton(window1, 195, 300, 150, 30);
  clear.setText("CLEAR LAYER");
  clear.addEventHandler(this, "clearClicked");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton addBattery; 
GButton addHorizontalWire; 
GButton addVertWire; 
GDropList selectLayer; 
GLabel batteryLabel; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GButton addLightbulb; 
GButton delete; 
GCheckbox showGrid; 
GButton clear; 
